// Texts of the administration pages, merged into the app's texts by i18n.ts.

export const adminEn = {
  users: "Users",
  invites: "Invites",
  serverKeys: "Server keys",
  usage: "Usage",
  serverSettings: "Settings",
  auditLog: "Audit log",
  role: "Role",
  status: "Status",
  roleMember: "Member",
  roleAdmin: "Admin",
  statusActive: "active",
  statusPending: "waiting for approval",
  statusUnverified: "email not confirmed",
  statusDisabled: "disabled",
  approve: "Approve",
  disable: "Disable",
  enable: "Enable",
  resetLink: "Reset link",
  resetLinkHint: "Send this link to the person; it works once for 2 hours:",
  resetTwoFactor: "Turn off two-factor",
  confirmResetTwoFactor: "Turn off two-factor sign-in for {name}? Only do this if you are sure it is really them.",
  mayUseServerKeys: "May use the server's keys",
  monthlyLimit: "Monthly limit in USD (empty = default)",
  invitesHint: "Without an email, anyone with the link can create one account.",
  emailOptional: "Email (optional)",
  createInvite: "Create invite",
  inviteLinkHint: "Send this link; it works once:",
  anyone: "anyone",
  withdraw: "Withdraw",
  serverKeysHint: "Keys of the server; who may use them is set under Settings and per user.",
  lastUsed: "last used",
  signUpAndSignIn: "Sign-up and sign-in",
  signUpMode: "Who may create an account",
  signUpInvite: "Only with an invite",
  signUpApproval: "Anyone, after an admin approves",
  signUpOpen: "Anyone",
  allowedDomains: "Only these email domains (empty = all)",
  passwordAccounts: "Accounts with email and password",
  adminTwoFactor: "Admins must use two-factor sign-in",
  limits: "Limits",
  limitsHint: "Sandbox limits apply to sandboxes started from now on.",
  projectsPerUser: "Projects per user (0 = no limit)",
  projectDiskMb: "Disk space per project in MB",
  sandboxCpus: "CPUs per sandbox",
  sandboxMemory: "Memory per sandbox (e.g. 4g)",
  sandboxPids: "Processes per sandbox",
  sandboxIdleMinutes: "Stop idle sandboxes after (minutes)",
  serverKeysFor: "Who may use the server's keys",
  forAdmins: "Only admins",
  forGranted: "Admins and users with a grant",
  forEveryone: "Everyone",
  defaultMonthlyLimit: "Default monthly limit per user in USD",
  when: "When",
  action: "Action",
  who: "Who",
  details: "Details",
};

export const adminDe: typeof adminEn = {
  users: "Nutzer",
  invites: "Einladungen",
  serverKeys: "Server-Schlüssel",
  usage: "Verbrauch",
  serverSettings: "Einstellungen",
  auditLog: "Protokoll",
  role: "Rolle",
  status: "Status",
  roleMember: "Mitglied",
  roleAdmin: "Admin",
  statusActive: "aktiv",
  statusPending: "wartet auf Freischaltung",
  statusUnverified: "E-Mail nicht bestätigt",
  statusDisabled: "gesperrt",
  approve: "Freischalten",
  disable: "Sperren",
  enable: "Entsperren",
  resetLink: "Link zum Zurücksetzen",
  resetLinkHint: "Schicke diesen Link an die Person; er gilt einmal für 2 Stunden:",
  resetTwoFactor: "Zwei-Faktor ausschalten",
  confirmResetTwoFactor: "Zwei-Faktor-Anmeldung für {name} ausschalten? Nur tun, wenn du sicher bist, dass es wirklich diese Person ist.",
  mayUseServerKeys: "Darf Server-Schlüssel nutzen",
  monthlyLimit: "Monatslimit in USD (leer = Standard)",
  invitesHint: "Ohne E-Mail kann jede Person mit dem Link ein Konto anlegen.",
  emailOptional: "E-Mail (optional)",
  createInvite: "Einladung erstellen",
  inviteLinkHint: "Schicke diesen Link; er gilt einmal:",
  anyone: "jede Person",
  withdraw: "Zurückziehen",
  serverKeysHint: "Schlüssel des Servers; wer sie nutzen darf, steht unter Einstellungen und je Nutzer.",
  lastUsed: "zuletzt genutzt",
  signUpAndSignIn: "Registrierung und Anmeldung",
  signUpMode: "Wer ein Konto anlegen darf",
  signUpInvite: "Nur mit Einladung",
  signUpApproval: "Jede Person, nach Freischaltung durch Admins",
  signUpOpen: "Jede Person",
  allowedDomains: "Nur diese E-Mail-Domains (leer = alle)",
  passwordAccounts: "Konten mit E-Mail und Passwort",
  adminTwoFactor: "Admins müssen die Zwei-Faktor-Anmeldung nutzen",
  limits: "Grenzen",
  limitsHint: "Sandbox-Grenzen gelten für Sandboxes, die ab jetzt starten.",
  projectsPerUser: "Projekte pro Nutzer (0 = unbegrenzt)",
  projectDiskMb: "Speicherplatz pro Projekt in MB",
  sandboxCpus: "CPUs pro Sandbox",
  sandboxMemory: "Arbeitsspeicher pro Sandbox (z. B. 4g)",
  sandboxPids: "Prozesse pro Sandbox",
  sandboxIdleMinutes: "Ungenutzte Sandboxes anhalten nach (Minuten)",
  serverKeysFor: "Wer die Server-Schlüssel nutzen darf",
  forAdmins: "Nur Admins",
  forGranted: "Admins und Nutzer mit Freigabe",
  forEveryone: "Alle",
  defaultMonthlyLimit: "Standard-Monatslimit pro Nutzer in USD",
  when: "Wann",
  action: "Aktion",
  who: "Wer",
  details: "Details",
};
