// Texts for Apple apps (the new-project option, the admin tab, the devices panel, the guideline
// reviews and the approval page), merged into the app's texts by i18n.ts.

export const appleEn = {
  sourceApple: "Apple app",
  appleAppHint:
    "A SwiftUI app for iPhone, iPad, Mac and Apple Watch. It is built on the server's Macs, and an independent reviewer checks it against Apple's guidelines.",
  bundleId: "Bundle ID (optional, e.g. com.yourname.app)",
  appleBuilds: "Apple",
  appleSettingsHint: "Apple apps are built and tested on Macs that connect to this server.",
  appleEnabled: "Build Apple apps on this server's Macs",
  appleAllowed: "Who may build Apple apps",
  appleMinutes: "Mac minutes per user and month (0 = no limit)",
  appleReviewerModel: "Model of the guideline reviewer, e.g. openai/gpt-5 (empty = Forge's choice)",
  macs: "Macs",
  macsHint: "A Mac connects to this server by itself. Add it here, then start forge-mac-worker on it.",
  addMac: "Add Mac",
  macTokenHint: "Shown only now: put this token into a file only you can read on the Mac, e.g. ~/.forge-mac-token, then run:",
  noMacs: "No Macs yet.",
  online: "online",
  offline: "offline",
  lastSeen: "last seen",
  appleJobs: "Jobs",
  noAppleJobs: "No jobs yet.",
  project: "Project",
  duration: "Duration",
  jobQueued: "waiting",
  jobRunning: "running",
  jobDone: "done",
  jobFailed: "failed",
  appleUsers: "Who may build",
  appleUsersHint: "Only counts when Apple builds are set to admins and users with a grant.",
  mayBuildApple: "May build Apple apps",
  minutesThisMonth: "Minutes this month",
  devices: "Devices",
  noScreens: "No screenshots yet. Ask Forge to build the app: its checks take a picture of every device.",
  light: "Light",
  dark: "Dark",
  reviewOfPrompt: "Apple review of the request",
  reviewOfPlan: "Apple review of the plan",
  reviewOfProduct: "Apple review of the app",
  verdictOk: "fits the guidelines",
  verdictConcern: "concerns",
  verdictViolation: "breaks the guidelines",
  areaSafety: "Safety",
  areaPerformance: "Performance",
  areaBusiness: "Business",
  areaDesign: "Design",
  areaLegal: "Legal",
  areaHig: "Human Interface Guidelines",
  findingsOk: "{n} areas without problems",
  fixHint: "Fix",
  guidelinesRead: "Read",
  readyForApproval: "Ready for approval",
  openApproval: "Open the approval page",
  approveApp: "Approve for Apple",
  sendBack: "Back to the agent",
  approvalWaiting: "Forge asks whether the app is ready for Apple. Look at every device and the reviews first.",
  approvalNotAsked: "Forge asks for your approval once the app builds, its tests pass and the reviewer has checked it.",
  approvedBy: "Approved by {who} on {when}",
  atCommit: "commit {commit}",
  uncommitted: "with uncommitted changes",
  approvalGone: "This question is no longer open. Reload the page.",
  guidelineReviews: "Guideline reviews",
  noReviews: "No reviews yet.",
  macBuilds: "Builds on the Macs",
  noBuilds: "No builds yet.",
  approvals: "Approvals",
  openChat: "Open the chat",
};

export const appleDe: typeof appleEn = {
  sourceApple: "Apple-App",
  appleAppHint:
    "Eine SwiftUI-App für iPhone, iPad, Mac und Apple Watch. Sie wird auf den Macs des Servers gebaut, und ein unabhängiger Prüfer vergleicht sie mit Apples Richtlinien.",
  bundleId: "Bundle-ID (optional, z. B. de.deinname.app)",
  appleBuilds: "Apple",
  appleSettingsHint: "Apple-Apps werden auf Macs gebaut und getestet, die sich mit diesem Server verbinden.",
  appleEnabled: "Apple-Apps auf den Macs dieses Servers bauen",
  appleAllowed: "Wer Apple-Apps bauen darf",
  appleMinutes: "Mac-Minuten pro Nutzer und Monat (0 = unbegrenzt)",
  appleReviewerModel: "Modell des Richtlinien-Prüfers, z. B. openai/gpt-5 (leer = Wahl von Forge)",
  macs: "Macs",
  macsHint: "Ein Mac verbindet sich selbst mit diesem Server. Lege ihn hier an und starte dann forge-mac-worker auf ihm.",
  addMac: "Mac hinzufügen",
  macTokenHint: "Nur jetzt sichtbar: Lege diesen Schlüssel auf dem Mac in eine Datei, die nur du lesen kannst, z. B. ~/.forge-mac-token, und starte dann:",
  noMacs: "Noch keine Macs.",
  online: "verbunden",
  offline: "nicht verbunden",
  lastSeen: "zuletzt gesehen",
  appleJobs: "Aufträge",
  noAppleJobs: "Noch keine Aufträge.",
  project: "Projekt",
  duration: "Dauer",
  jobQueued: "wartet",
  jobRunning: "läuft",
  jobDone: "fertig",
  jobFailed: "fehlgeschlagen",
  appleUsers: "Wer bauen darf",
  appleUsersHint: "Gilt nur, wenn Apple-Builds für Admins und Nutzer mit Freigabe eingestellt sind.",
  mayBuildApple: "Darf Apple-Apps bauen",
  minutesThisMonth: "Minuten diesen Monat",
  devices: "Geräte",
  noScreens: "Noch keine Bildschirmfotos. Bitte Forge, die App zu bauen: Die Prüfung fotografiert jedes Gerät.",
  light: "Hell",
  dark: "Dunkel",
  reviewOfPrompt: "Apple-Prüfung der Anfrage",
  reviewOfPlan: "Apple-Prüfung des Plans",
  reviewOfProduct: "Apple-Prüfung der App",
  verdictOk: "entspricht den Richtlinien",
  verdictConcern: "Bedenken",
  verdictViolation: "verstößt gegen die Richtlinien",
  areaSafety: "Sicherheit",
  areaPerformance: "Leistung",
  areaBusiness: "Geschäftliches",
  areaDesign: "Design",
  areaLegal: "Rechtliches",
  areaHig: "Human Interface Guidelines",
  findingsOk: "{n} Bereiche ohne Probleme",
  fixHint: "Lösung",
  guidelinesRead: "Gelesen",
  readyForApproval: "Zur Freigabe",
  openApproval: "Zur Freigabe öffnen",
  approveApp: "Für Apple freigeben",
  sendBack: "Zurück an den Agenten",
  approvalWaiting: "Forge fragt, ob die App bereit für Apple ist. Schau dir vorher jedes Gerät und die Prüfungen an.",
  approvalNotAsked: "Forge fragt nach deiner Freigabe, sobald die App gebaut ist, ihre Tests bestehen und der Prüfer sie angesehen hat.",
  approvedBy: "Freigegeben von {who} am {when}",
  atCommit: "Commit {commit}",
  uncommitted: "mit nicht committeten Änderungen",
  approvalGone: "Diese Frage ist nicht mehr offen. Lade die Seite neu.",
  guidelineReviews: "Richtlinien-Prüfungen",
  noReviews: "Noch keine Prüfungen.",
  macBuilds: "Builds auf den Macs",
  noBuilds: "Noch keine Builds.",
  approvals: "Freigaben",
  openChat: "Zum Chat",
};
