// Texts for Apple apps (the new-project option, the admin tab and the devices panel), merged into
// the app's texts by i18n.ts.

export const appleEn = {
  sourceApple: "Apple app",
  appleAppHint:
    "A SwiftUI app for iPhone, iPad, Mac and Apple Watch. It is built on the server's Macs, and an independent reviewer checks it against Apple's guidelines.",
  bundleId: "Bundle ID (optional, e.g. com.yourname.app)",
  appleBuilds: "Apple",
  appleSettingsHint: "Apple apps are built and tested on Macs that connect to this server.",
  appleEnabled: "Build Apple apps on this server's Macs",
  appleAllowed: "Who may build Apple apps",
  appleMinutes: "Mac minutes per user and month (0 = no limit)",
  appleReviewerModel: "Model of the guideline reviewer, e.g. openai/gpt-5 (empty = Forge's choice)",
  macs: "Macs",
  macsHint: "A Mac connects to this server by itself. Add it here, then start forge-mac-worker on it.",
  addMac: "Add Mac",
  macTokenHint: "Shown only now: put this token into a file only you can read on the Mac, e.g. ~/.forge-mac-token, then run:",
  noMacs: "No Macs yet.",
  online: "online",
  offline: "offline",
  lastSeen: "last seen",
  appleJobs: "Jobs",
  noAppleJobs: "No jobs yet.",
  project: "Project",
  duration: "Duration",
  jobQueued: "waiting",
  jobRunning: "running",
  jobDone: "done",
  jobFailed: "failed",
  appleUsers: "Who may build",
  appleUsersHint: "Only counts when Apple builds are set to admins and users with a grant.",
  mayBuildApple: "May build Apple apps",
  minutesThisMonth: "Minutes this month",
  devices: "Devices",
  noScreens: "No screenshots yet. Ask Forge to build the app: its checks take a picture of every device.",
  light: "Light",
  dark: "Dark",
};

export const appleDe: typeof appleEn = {
  sourceApple: "Apple-App",
  appleAppHint:
    "Eine SwiftUI-App für iPhone, iPad, Mac und Apple Watch. Sie wird auf den Macs des Servers gebaut, und ein unabhängiger Prüfer vergleicht sie mit Apples Richtlinien.",
  bundleId: "Bundle-ID (optional, z. B. de.deinname.app)",
  appleBuilds: "Apple",
  appleSettingsHint: "Apple-Apps werden auf Macs gebaut und getestet, die sich mit diesem Server verbinden.",
  appleEnabled: "Apple-Apps auf den Macs dieses Servers bauen",
  appleAllowed: "Wer Apple-Apps bauen darf",
  appleMinutes: "Mac-Minuten pro Nutzer und Monat (0 = unbegrenzt)",
  appleReviewerModel: "Modell des Richtlinien-Prüfers, z. B. openai/gpt-5 (leer = Wahl von Forge)",
  macs: "Macs",
  macsHint: "Ein Mac verbindet sich selbst mit diesem Server. Lege ihn hier an und starte dann forge-mac-worker auf ihm.",
  addMac: "Mac hinzufügen",
  macTokenHint: "Nur jetzt sichtbar: Lege diesen Schlüssel auf dem Mac in eine Datei, die nur du lesen kannst, z. B. ~/.forge-mac-token, und starte dann:",
  noMacs: "Noch keine Macs.",
  online: "verbunden",
  offline: "nicht verbunden",
  lastSeen: "zuletzt gesehen",
  appleJobs: "Aufträge",
  noAppleJobs: "Noch keine Aufträge.",
  project: "Projekt",
  duration: "Dauer",
  jobQueued: "wartet",
  jobRunning: "läuft",
  jobDone: "fertig",
  jobFailed: "fehlgeschlagen",
  appleUsers: "Wer bauen darf",
  appleUsersHint: "Gilt nur, wenn Apple-Builds für Admins und Nutzer mit Freigabe eingestellt sind.",
  mayBuildApple: "Darf Apple-Apps bauen",
  minutesThisMonth: "Minuten diesen Monat",
  devices: "Geräte",
  noScreens: "Noch keine Bildschirmfotos. Bitte Forge, die App zu bauen: Die Prüfung fotografiert jedes Gerät.",
  light: "Hell",
  dark: "Dunkel",
};
