// Texts for the App Store listing page, merged by i18n.ts.

export const listingEn = {
  listingTitle: "Store texts",
  reviewOfListing: "Apple review of the store texts",
  openListing: "Store texts",
  listingHint:
    "What the App Store shows. Forge drafted it after your approval and the independent reviewer checked it; finish it here. The URLs are always yours: Forge never makes them up.",
  listingNone: "Forge has not drafted the store texts yet. It does so after you approve the app.",
  listingFromDraft: "Forge's draft (not saved yet)",
  listingSaved: "Saved {when}",
  listingSave: "Save",
  listingRedraft: "Take Forge's newest draft",
  listingLocale: "Language (e.g. en-US, de-DE)",
  listingName: "Name",
  listingSubtitle: "Subtitle",
  listingDescription: "Description",
  listingKeywords: "Keywords (comma-separated)",
  listingPromo: "Promotional text",
  listingWhatsNew: "What's new (leave empty for the first version)",
  listingCopyright: "Copyright (e.g. 2026 Your Name)",
  listingCategory: "Category",
  listingSecondCategory: "Second category",
  listingNoCategory: "none",
  listingSupportUrl: "Support URL",
  listingMarketingUrl: "Marketing URL (optional)",
  listingPrivacyUrl: "Privacy policy URL",
  listingAgeRating: "Age rating answers",
  listingPrivacy: "App privacy (enter these by hand in App Store Connect → App Privacy)",
  listingNoData: "The app collects no data.",
  listingNotes: "For you to check",
  listingMissing: "Before Apple: {what}",
  listingCount: "{n} of {max}",
  frequencyNONE: "none",
  frequencyINFREQUENT: "infrequent or mild",
  frequencyFREQUENT: "frequent or intense",
};

export const listingDe: typeof listingEn = {
  listingTitle: "Store-Texte",
  reviewOfListing: "Apple-Prüfung der Store-Texte",
  openListing: "Store-Texte",
  listingHint:
    "Was der App Store zeigt. Forge hat es nach deiner Freigabe entworfen, der unabhängige Prüfer hat es geprüft; hier machst du es fertig. Die URLs sind immer deine: Forge erfindet sie nie.",
  listingNone: "Forge hat die Store-Texte noch nicht entworfen. Das macht es nach deiner Freigabe der App.",
  listingFromDraft: "Entwurf von Forge (noch nicht gespeichert)",
  listingSaved: "Gespeichert {when}",
  listingSave: "Speichern",
  listingRedraft: "Neuesten Entwurf von Forge übernehmen",
  listingLocale: "Sprache (z. B. de-DE, en-US)",
  listingName: "Name",
  listingSubtitle: "Untertitel",
  listingDescription: "Beschreibung",
  listingKeywords: "Schlüsselwörter (mit Komma getrennt)",
  listingPromo: "Werbetext",
  listingWhatsNew: "Neuerungen (bei der ersten Version leer lassen)",
  listingCopyright: "Copyright (z. B. 2026 Dein Name)",
  listingCategory: "Kategorie",
  listingSecondCategory: "Zweite Kategorie",
  listingNoCategory: "keine",
  listingSupportUrl: "Support-URL",
  listingMarketingUrl: "Marketing-URL (optional)",
  listingPrivacyUrl: "URL der Datenschutzerklärung",
  listingAgeRating: "Antworten zur Altersfreigabe",
  listingPrivacy: "App-Datenschutz (von Hand in App Store Connect → App-Datenschutz eintragen)",
  listingNoData: "Die App erhebt keine Daten.",
  listingNotes: "Bitte prüfen",
  listingMissing: "Vor Apple noch: {what}",
  listingCount: "{n} von {max}",
  frequencyNONE: "nie",
  frequencyINFREQUENT: "selten oder schwach",
  frequencyFREQUENT: "häufig oder stark",
};
