// Texts for releasing an Apple app (TestFlight now, the App Store later), merged by i18n.ts.

export const releaseEn = {
  releaseTitle: "Release",
  openRelease: "To the release",
  releaseHint:
    "Forge builds exactly the approved commit, signs it on a Mac in a VM of its own and uploads it to App Store Connect. The build then appears in TestFlight for your team.",
  releaseNeedsApproval: "Approve the app first (Ready for approval). A release builds exactly the approved commit.",
  releaseNeedsKey: "Add your App Store Connect team key first.",
  releaseKeyLink: "Settings → App Store Connect",
  releaseApproved: "Approved commit {commit}",
  releaseIos: "To TestFlight: iPhone, iPad and Watch",
  releaseMac: "To TestFlight: Mac",
  releaseBoth: "Both",
  releases: "Releases",
  noReleases: "No releases yet.",
  releaseBuild: "Version {version}, build {build}",
  releaseRetry: "Start again from here",
  releaseRunning: "in progress",
  releaseDone: "in TestFlight",
  releaseFailed: "stopped",
  stepArchive: "Archive the approved commit",
  stepIdentify: "Find the app in App Store Connect",
  stepExport: "Sign it (fresh VM)",
  stepUpload: "Upload to Apple",
  stepProcess: "Apple processes the build",
  stepTestflight: "TestFlight group",
  stepDone: "Ready in TestFlight",
  platformIos: "iPhone, iPad, Watch",
  platformMacos: "Mac",
};

export const releaseDe: typeof releaseEn = {
  releaseTitle: "Veröffentlichen",
  openRelease: "Zum Veröffentlichen",
  releaseHint:
    "Forge baut genau den freigegebenen Commit, signiert ihn auf einem Mac in einer eigenen VM und lädt ihn zu App Store Connect hoch. Danach erscheint der Build in TestFlight für dein Team.",
  releaseNeedsApproval: "Gib die App zuerst frei (Zur Freigabe). Veröffentlicht wird genau der freigegebene Commit.",
  releaseNeedsKey: "Hinterlege zuerst deinen App-Store-Connect-Teamschlüssel.",
  releaseKeyLink: "Einstellungen → App Store Connect",
  releaseApproved: "Freigegebener Commit {commit}",
  releaseIos: "Zu TestFlight: iPhone, iPad und Watch",
  releaseMac: "Zu TestFlight: Mac",
  releaseBoth: "Beides",
  releases: "Veröffentlichungen",
  noReleases: "Noch keine Veröffentlichungen.",
  releaseBuild: "Version {version}, Build {build}",
  releaseRetry: "Ab hier neu starten",
  releaseRunning: "läuft",
  releaseDone: "in TestFlight",
  releaseFailed: "angehalten",
  stepArchive: "Freigegebenen Commit archivieren",
  stepIdentify: "App in App Store Connect finden",
  stepExport: "Signieren (frische VM)",
  stepUpload: "Zu Apple hochladen",
  stepProcess: "Apple verarbeitet den Build",
  stepTestflight: "TestFlight-Gruppe",
  stepDone: "Bereit in TestFlight",
  platformIos: "iPhone, iPad, Watch",
  platformMacos: "Mac",
};
