// Texts for the App Store step of the release page, merged by i18n.ts.

export const submitEn = {
  appStoreStep: "App Store",
  storeStepHint:
    "Forge fills the version in App Store Connect (texts, screenshots of every device, age rating, a free price, every country, the contact for App Review) — nothing goes to App Review before you confirm it.",
  appStoreOnce: "Once in App Store Connect, by hand: accept the agreements, set your EU trader status (DSA), and answer App Privacy.",
  reviewContact: "Contact for App Review",
  contactFirst: "First name",
  contactLast: "Last name",
  contactPhone: "Phone (e.g. +49 30 1234567)",
  contactEmail: "Email",
  contactNotes: "Notes for App Review (optional)",
  prepareForStore: "Prepare for the App Store",
  noTestflight: "A release in TestFlight comes first.",
  submitToApple: "Submit to Apple",
  submitConfirm: "Submit {name} version {version} to Apple's App Review now? Apple reviews exactly what is in App Store Connect.",
  releaseOnStore: "Release on the App Store",
  releaseConfirm: "Put version {version} on the App Store now?",
  submissionPreparing: "being prepared",
  submissionReady: "ready — waiting for your submission",
  submissionFailed: "stopped",
  submissionSubmitted: "at App Review",
  submissionReleased: "released",
  appleSays: "Apple: {state}",
  shotsUploaded: "{n} screenshots",
  stepScreenshots: "Store screenshots of every device",
  stepVersionStore: "Version with the build",
  stepTexts: "Texts, categories, age rating",
  stepTerms: "Rights, price, countries",
  stepContact: "Contact for App Review",
  stepPlacements: "Screenshots placed",
};

export const submitDe: typeof submitEn = {
  appStoreStep: "App Store",
  storeStepHint:
    "Forge füllt die Version in App Store Connect aus (Texte, Bildschirmfotos aller Geräte, Altersfreigabe, kostenlos, alle Länder, Kontakt für App Review) — zum App Review geht nichts, bevor du es bestätigst.",
  appStoreOnce: "Einmal von Hand in App Store Connect: Vereinbarungen annehmen, EU-Händlerstatus (DSA) angeben und App-Datenschutz beantworten.",
  reviewContact: "Kontakt für App Review",
  contactFirst: "Vorname",
  contactLast: "Nachname",
  contactPhone: "Telefon (z. B. +49 30 1234567)",
  contactEmail: "E-Mail",
  contactNotes: "Hinweise für App Review (optional)",
  prepareForStore: "Für den App Store vorbereiten",
  noTestflight: "Zuerst braucht es ein Release in TestFlight.",
  submitToApple: "Bei Apple einreichen",
  submitConfirm: "{name} Version {version} jetzt bei Apples App Review einreichen? Apple prüft genau das, was in App Store Connect steht.",
  releaseOnStore: "Im App Store veröffentlichen",
  releaseConfirm: "Version {version} jetzt im App Store veröffentlichen?",
  submissionPreparing: "wird vorbereitet",
  submissionReady: "bereit — wartet auf deine Einreichung",
  submissionFailed: "angehalten",
  submissionSubmitted: "beim App Review",
  submissionReleased: "veröffentlicht",
  appleSays: "Apple: {state}",
  shotsUploaded: "{n} Bildschirmfotos",
  stepScreenshots: "Store-Bildschirmfotos aller Geräte",
  stepVersionStore: "Version mit dem Build",
  stepTexts: "Texte, Kategorien, Altersfreigabe",
  stepTerms: "Rechte, Preis, Länder",
  stepContact: "Kontakt für App Review",
  stepPlacements: "Bildschirmfotos platziert",
};
