"""`forge config schema --markdown`: the configuration reference, generated from ForgeConfig.

docs/config.md is this output; a test keeps them equal, so the reference cannot drift.
"""

import json
import types
import typing
from typing import Any, Literal, get_args, get_origin

from pydantic import BaseModel
from pydantic_core import PydanticUndefined

from forge.config import (
    DEFAULT_ROLES,
    AppleConfig,
    ApprovalConfig,
    BrowserConfig,
    ForgeConfig,
    HookConfig,
    LimitsConfig,
    McpServerConfig,
    ModelOverride,
    PermissionsConfig,
    ProviderConfig,
    SandboxConfig,
    WebConfig,
)

INTRO = """\
# Configuration reference

Generated by `forge config schema --markdown` from `ForgeConfig` in `src/forge/config.py`.

Forge reads, later files winning: built-in defaults, `~/.forge/forge.toml`, the project's
`.forge/config.toml`, the selected profile (`-p NAME` or `profile = "NAME"`), `FORGE_*`
environment variables (`FORGE_SANDBOX__MODE=read-only`; `__` separates levels), then CLI
flags. A project file may set `[providers]`, `[mcp_servers]` and `[hooks]` only after
`forge trust`. `forge config check` prints the effective configuration (secrets masked).
"""

DOCS: dict[str, str] = {
    "profile": "Profile to apply from `[profiles.*]` (`-p` overrides it).",
    "providers": "Model endpoints by name; see `[providers.<name>]`. Common providers have presets.",
    "models": 'Capability and price overrides per `"provider/model"`.',
    "roles": 'Model fallback chain per role: `coder = ["anthropic/claude-sonnet", "openai/gpt-5"]`.',
    "sandbox": "See `[sandbox]`.",
    "approval": "See `[approval]`.",
    "permissions": "See `[permissions]`.",
    "limits": "See `[limits]`.",
    "web": "See `[web]`.",
    "browser": "See `[browser]`.",
    "apple": "See `[apple]`.",
    "headless": "Run the browser without a window.",
    "channel": "Use an installed browser (`chrome`, `msedge`) instead of Playwright's Chromium.",
    "executable": "Path of a Chromium-based browser to start instead.",
    "viewport_width": "Page width in pixels (screenshots have this size).",
    "viewport_height": "Page height in pixels.",
    "timeout_s": "Seconds a page load or action may take.",
    "max_screenshots": "Screenshots per browser agent; later actions return text only.",
    "mcp_servers": "MCP servers to connect; see `[mcp_servers.<name>]`.",
    "hooks": "Shell hooks per event: session_start, prompt_submit, pre_tool, post_tool, step_done, pre_compact, stop, subagent_stop.",
    "profiles": 'Named overlays, e.g. `[profiles.ci] approval = { policy = "never" }`.',
    "kind": "Adapter: `openai_compat`, `anthropic`, `google` or `litellm`.",
    "wire": "For `openai_compat`: Chat Completions (`chat`) or Responses (`responses`).",
    "base_url": "API URL; `bedrock://<region>` and `vertex://<project>/<region>` select those clouds.",
    "api_key_env": "Environment variable holding the API key (keys are never stored in config).",
    "headers": "Extra HTTP headers.",
    "context_window": "Tokens the model accepts.",
    "max_output": "Tokens the model may write per answer.",
    "tools": "Native tool calling (false: prompt-based tools are used).",
    "parallel_tools": "Several tool calls per answer.",
    "vision": "Reads images.",
    "reasoning": "Thinks before answering (reasoning effort is sent).",
    "prompt_cache": "Caches the stable prompt prefix.",
    "web_search": "Has a native web search tool.",
    "cost_in": "USD per 1M input tokens.",
    "cost_out": "USD per 1M output tokens.",
    "mode": "`read-only`, `workspace-write` (project + temp folders) or `full-access` (no sandbox).",
    "network": "Allow outgoing network from shell commands.",
    "writable_roots": "Extra folders commands and file tools may write to.",
    "policy": "`on-request` (ask when leaving the sandbox), `always` (ask before changes) or `never`.",
    "allow": "Rules that run without asking, e.g. `bash(git status*)`.",
    "ask": "Rules that always ask, e.g. `bash(git push *)`.",
    "deny": "Rules that are refused, e.g. `bash(rm -rf *)`, `read_file(./.env*)`.",
    "max_turns_per_step": "Model turns an agent gets per plan step.",
    "max_step_attempts": "Check failures before a step counts as failed.",
    "max_clarify_rounds": "Rounds of clarifying questions.",
    "max_parallel_agents": "Sub-agents running at the same time.",
    "max_cost_usd": "Budget for the whole session; work stops cleanly when it is used.",
    "compact_at": "Share of the context window at which old turns are summarized.",
    "reset_at": "Share of the context window at which the context is rebuilt from the plan.",
    "mcp_defer_threshold": "Above this many MCP tools, schemas load on demand via `tool_search`.",
    "max_web_searches": "Web searches per session.",
    "search_backend": "`native` (the model's own search), `brave`, `tavily` or `searxng`.",
    "search_api_key_env": "Variable with the backend's API key (for `searxng`: its URL).",
    "fallback_backend": "Backend for `native` when the model has no search tool of its own (uses `search_api_key_env`).",
    "command": "Command line (list) of a stdio server, or the shell command of a hook.",
    "env_keys": "Environment variables passed to the server.",
    "url": "URL of an HTTP (streamable) server.",
    "headers_env": "HTTP header -> environment variable holding its value.",
    "match": "Regex on the tool name (tool events only; empty = every tool).",
}

# Fields whose name another section already uses with a different meaning.
SECTION_DOCS: dict[type[BaseModel], dict[str, str]] = {
    AppleConfig: {
        "timeout_s": "Seconds one build, test run or archive may take.",
        "max_screenshots": "Simulator and Mac screenshots per session.",
        "devices": "Simulator per platform (`ios`, `ipados`, `watchos`); "
        "the newest of the same family when it is missing.",
    },
}

SECTIONS: list[tuple[str, type[BaseModel], str]] = [
    ("[sandbox]", SandboxConfig, ""),
    ("[approval]", ApprovalConfig, ""),
    ("[permissions]", PermissionsConfig, ""),
    ("[limits]", LimitsConfig, ""),
    ("[web]", WebConfig, ""),
    (
        "[browser]",
        BrowserConfig,
        "Install Chromium once with `forge browser install`, or set `channel`.",
    ),
    (
        "[apple]",
        AppleConfig,
        "Needs a Mac with Xcode (`xcodebuild`) and XcodeGen (`brew install xcodegen`).",
    ),
    ("[providers.<name>]", ProviderConfig, "One table per provider name."),
    (
        '[models."<provider>/<model>"]',
        ModelOverride,
        "Unset fields keep the built-in catalog value.",
    ),
    ("[mcp_servers.<name>]", McpServerConfig, "Set `command` (stdio) or `url` (HTTP)."),
    (
        "[hooks] entries",
        HookConfig,
        'Written as `post_tool = [{ match = "edit_file", command = "ruff format {path}" }]`.',
    ),
]


def type_name(annotation: Any) -> str:
    """A short, readable type for the reference tables."""
    origin, args = get_origin(annotation), get_args(annotation)
    if origin is Literal:
        return " \\| ".join(f"`{a}`" for a in args)
    if origin in (types.UnionType, typing.Union):
        named = [type_name(a) for a in args if a is not type(None)]
        return " \\| ".join(named) + (" (optional)" if type(None) in args else "")
    if origin is list:
        return f"list of {type_name(args[0])}"
    if origin is dict:
        return f"table of {type_name(args[1])}"
    return getattr(annotation, "__name__", str(annotation))


def default_text(value: Any) -> str:
    """A default as TOML-ish text."""
    if value is PydanticUndefined or isinstance(value, BaseModel):
        return "-"
    if value is None:
        return "unset"
    return f"`{json.dumps(value)}`"


def table(model: type[BaseModel]) -> list[str]:
    """One row per field: key, type, default, description."""
    rows = ["| key | type | default | description |", "| --- | --- | --- | --- |"]
    docs = DOCS | SECTION_DOCS.get(model, {})
    for name, field in model.model_fields.items():
        rows.append(
            f"| `{name}` | {type_name(field.annotation)} | {default_text(field.default)} | {docs.get(name, '')} |"
        )
    return rows


def config_markdown() -> str:
    """The whole reference."""
    lines = [INTRO, "## Top level", "", *table(ForgeConfig), ""]
    lines += ["## [roles]", "", "Built-in defaults:", "", "```toml", "[roles]"]
    lines += [f"{role} = {json.dumps(chain)}" for role, chain in DEFAULT_ROLES.items()]
    lines += ["```", ""]
    for title, model, note in SECTIONS:
        lines += [f"## {title}", "", (model.__doc__ or "").strip()]
        lines += [note, "", *table(model), ""] if note else ["", *table(model), ""]
    return "\n".join(lines).rstrip() + "\n"
